import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, ArrowUp, BookOpen, Check, CheckCircle2, ChevronRight, FileText, Layers, MessageCircle, RotateCcw, ShieldCheck, Sparkles, X} from 'lucide-react';
import {answerQuestion,documents,prompts,steps} from './knowledge';
import './styles.css';

function DocumentDialog({selection,onClose}) {
 const dialog=useRef(null);
 const doc=documents.find(d=>d.id===selection.doc);
 useEffect(()=>{const previous=document.activeElement;dialog.current.showModal();return()=>previous?.focus();},[]);
 return <dialog ref={dialog} onCancel={onClose} aria-labelledby="document-title" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="document-head"><div><p className="eyebrow">BIBLIOTECA DE DEMOSTRACIÓN</p><h2 id="document-title">{doc.title}</h2></div><button className="icon-button" aria-label="Cerrar documento" onClick={onClose}><X size={20}/></button></div><p className="document-note">Contenido ficticio de Aurora Demo · Referencias de ejemplo</p>{doc.pages.filter(p=>!selection.page||p.number===selection.page).map(p=><section className="document-page" key={p.number}><span>PÁGINA {p.number}</span><h3>{p.title}</h3><p>{p.text}</p></section>)}<button className="outline-button" onClick={onClose}>Volver a Lia</button></dialog>;
}
function App(){
 const [messages,setMessages]=useState([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[selection,setSelection]=useState(null),[tab,setTab]=useState('chat');
 const [completed,setCompleted]=useState(()=>{try{const v=JSON.parse(localStorage.getItem('lia-demo-progress')||'[]');return Array.isArray(v)?v.filter(n=>Number.isInteger(n)&&n>=0&&n<steps.length):[];}catch{return [];}});
 const timer=useRef(null), bottom=useRef(null), locked=useRef(false),[storageNotice,setStorageNotice]=useState('');
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 useEffect(()=>{if(messages.length)bottom.current?.scrollIntoView({behavior:'auto',block:'nearest'});},[messages,busy]);
 function ask(question){const q=question.trim();if(!q||locked.current||q.length>500)return;locked.current=true;setBusy(true);setInput('');setMessages(old=>[...old,{role:'user',text:q}]);timer.current=setTimeout(()=>{setMessages(old=>[...old,{role:'lia',...answerQuestion(q)}]);setBusy(false);locked.current=false;},650);}
 function reset(){clearTimeout(timer.current);locked.current=false;setBusy(false);setMessages([]);setInput('');}
 function toggleStep(index){const next=completed.includes(index)?completed.filter(i=>i!==index):[...completed,index];setCompleted(next);try{localStorage.setItem('lia-demo-progress',JSON.stringify(next));}catch{setStorageNotice('El progreso se conserva solo durante esta sesión.');}}
 return <div className="app-shell"><aside className="sidebar"><a href="#" className="logo" onClick={e=>{e.preventDefault();setTab('chat');}}><span className="logo-symbol"><Sparkles size={22}/></span>lia<span className="logo-period">.</span></a><div className="org"><span>A</span><div><strong>Aurora Demo</strong><small>Un nuevo comienzo</small></div><ChevronRight size={14}/></div><p className="nav-caption">TU ESPACIO</p><nav aria-label="Secciones de Lia"><button className={tab==='chat'?'active':''} aria-pressed={tab==='chat'} onClick={()=>setTab('chat')}><MessageCircle size={17}/>Mi asistente<span className="live-dot"/></button><button className={tab==='docs'?'active':''} aria-pressed={tab==='docs'} onClick={()=>setTab('docs')}><BookOpen size={17}/>Biblioteca<span className="nav-number">02</span></button></nav><div className="sidebar-art" aria-hidden="true"><div className="orbit o1"/><div className="orbit o2"/><div className="orbit o3"/><div className="orbit-core">✦</div><span className="satellite s1"/><span className="satellite s2"/></div><div className="sidebar-copy"><h3>El conocimiento conecta.</h3><p>Encuentra lo que necesitas para dar tu siguiente paso.</p></div><a className="back-link" href="/#lia">Volver al portafolio <ArrowUpRight size={14}/></a><div className="visitor"><span>V</span><div><strong>Visitante</strong><small>Explorando la demo</small></div></div></aside>
 <main><header className="topbar"><span>ONBOARDING <i>/</i> {tab==='chat'?'MI ASISTENTE':'BIBLIOTECA'}</span><div className="demo-pill"><span/>Demo simulada</div></header><div className="page"><div className="page-heading"><div><p className="eyebrow">TU PRIMER DÍA, ACOMPAÑADO</p><h1>{tab==='chat'?'Cada comienzo, más claro.':'Todo empieza por el contexto.'}</h1><p>{tab==='chat'?'Pregunta, encuentra una fuente y sigue adelante. Lia te acompaña.':'Explora los documentos ficticios que respaldan las respuestas de esta demo.'}</p></div><span className="edition">LIA / 01<br/><b>CONOCIMIENTO COMPARTIDO</b></span></div>
 {tab==='chat'?<div className="workspace-grid"><section className="chat-card" aria-label="Conversación con Lia"><div className="chat-header"><div className="bot-avatar"><Sparkles size={19}/></div><div><h2>Lia, tu guía de onboarding</h2><p><span/>Respuestas con contexto</p></div><button className="icon-button" title="Nueva conversación" aria-label="Nueva conversación" onClick={reset}><RotateCcw size={17}/></button></div><div className="conversation" role="log" aria-live="polite" aria-busy={busy}>{messages.length===0?<div className="welcome"><div className="welcome-symbol"><Sparkles size={33}/><span/></div><p className="eyebrow">HOLA, QUÉ BUENO TENERTE AQUÍ</p><h2>Tu próximo paso<br/>empieza con una pregunta.</h2><p>Conoce al equipo, ubica lo importante y<br className="desktop-break"/> empieza con tranquilidad.</p><div className="prompt-grid">{prompts.map((q,i)=><button key={q} onClick={()=>ask(q)}><span className="prompt-icon">{i===0?<Layers size={17}/>:i===1?<BookOpen size={17}/>:i===2?<ShieldCheck size={17}/>:<MessageCircle size={17}/>}</span>{q}<ArrowUpRight size={14}/></button>)}</div></div>:messages.map((m,i)=><div className={'message '+m.role} key={i}>{m.role==='lia'&&<span className="message-icon"><Sparkles size={15}/></span>}<div className="message-body"><small>{m.role==='lia'?'LIA · RESPUESTA SIMULADA':'TÚ'}</small><p>{m.text}</p>{m.role==='lia'&&(m.supported?<div className="sources"><p><CheckCircle2 size={13}/>Fuente de este ejemplo</p>{m.sources.map(s=><details key={s.doc+s.page}><summary><FileText size={14}/>{s.title}<span>Pág. {s.page}</span><ChevronRight size={13}/></summary><blockquote>{s.quote}</blockquote><button onClick={()=>setSelection({doc:s.doc,page:s.page})}>Leer página de referencia <ArrowUpRight size={13}/></button></details>)}</div>:<span className="no-evidence">Sin evidencia suficiente</span>)}</div></div>)}{busy&&<div className="thinking"><Sparkles size={15}/>Consultando el ejemplo…</div>}<div ref={bottom}/></div><div className="composer"><form onSubmit={e=>{e.preventDefault();ask(input);}}><input aria-label="Pregunta para Lia" placeholder="¿Qué te gustaría saber?" value={input} maxLength={500} onChange={e=>setInput(e.target.value)}/><button type="submit" aria-label="Enviar pregunta" disabled={busy||!input.trim()}><ArrowUp size={19}/></button></form><p><ShieldCheck size={12}/>Ejemplos predefinidos · Sin conexión a un modelo de IA</p></div></section>
 <aside className="context-column"><section className="context-card"><p className="eyebrow">EL CONTEXTO IMPORTA</p><h2>Una respuesta.<br/>Una fuente.</h2><p>Las respuestas de ejemplo se acompañan del fragmento utilizado. Puedes abrirlo y comprobarlo.</p><div className="context-stat"><span>02</span><div>documentos ficticios<br/><small>Disponibles para explorar</small></div><BookOpen size={23}/></div>{documents.map(d=><button className="document-link" key={d.id} onClick={()=>setSelection({doc:d.id})}><FileText size={16}/><div><b>{d.title}</b><small>{d.pages.length} páginas · Documento de ejemplo</small></div><ChevronRight size={14}/></button>)}</section><section className="journey-card"><div className="journey-heading"><h3>Tu ruta de bienvenida</h3><span>{completed.length}/{steps.length}</span></div><div className="progress-track"><span style={{width:completed.length/steps.length*100+'%'}}/></div>{steps.map((s,i)=><label className={completed.includes(i)?'done':''} key={s}><input type="checkbox" checked={completed.includes(i)} onChange={()=>toggleStep(i)}/><span>{s}</span></label>)}<p>{completed.length===steps.length?'¡Terminaste tu recorrido de demostración!':'Marca cada paso a tu ritmo.'}</p>{storageNotice&&<p role="status">{storageNotice}</p>}</section><div className="honesty-note"><ShieldCheck size={17}/><p>Datos ficticios. La demo muestra la experiencia; no es un sistema de RR. HH. en producción.</p></div></aside></div>:<section className="library">{documents.map(d=><article key={d.id}><span className="library-icon"><FileText size={27}/></span><p className="eyebrow">{d.tag}</p><h2>{d.title}</h2><p>{d.pages.length} páginas con información ficticia de Aurora Demo.</p><button className="outline-button" onClick={()=>setSelection({doc:d.id})}>Explorar documento <ArrowUpRight size={15}/></button></article>)}<div className="library-note"><h3>Cómo funciona esta demostración</h3><p>Las preguntas de ejemplo devuelven respuestas predefinidas y sus fuentes. Las preguntas no reconocidas muestran una abstención. La aplicación privada de Lia integra Python y Ollama; aquí se presenta una experiencia simulada, sin documentos empresariales ni datos de empleados.</p></div></section>}
 <footer><span>Lia · Un inicio con respuestas.</span><span>PROYECTO DE ANDRÉS SALAZAR <span className="footer-dot">✦</span></span></footer></div></main>{selection&&<DocumentDialog selection={selection} onClose={()=>setSelection(null)}/>}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
